export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS'
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL'
export const CATEGORY_REMOVE_SUCCESS = 'CATEGORY_REMOVE_SUCCESS'
export const CATEGORY_REMOVE_FAIL = 'CATEGORY_REMOVE_FAIL'