export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCES = 'LOGIN_SUCCES'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'

export const REGISTR_REQUEST = 'REGISTR_REQUEST'
export const REGISTR_SUCCES = 'REGISTR_SUCCES'
export const REGISTER_FAIL = 'REGISTER_FAIL'


export const LOAD_PHOTO = 'LOAD_PHOTO'